export const SEGMENTS = [
  // ENGAGEMENT & ACTIVITY (14 segments)
  {
    id: "engaged-30-days",
    name: "📧 Engaged (Last 30 Days)",
    description: "Opened or clicked email in last 30 days",
    category: "Engagement & Activity",
    icon: "📧",
    definition: "Opened or clicked email within 30 days",
  },
  {
    id: "engaged-60-days",
    name: "📬 Engaged (Last 60 Days)",
    description: "Opened or clicked email in last 60 days",
    category: "Engagement & Activity",
    icon: "📬",
    definition: "Opened or clicked email within 60 days",
  },
  {
    id: "engaged-90-days",
    name: "📮 Engaged (Last 90 Days)",
    description: "Opened or clicked email in last 90 days",
    category: "Engagement & Activity",
    icon: "📮",
    definition: "Opened or clicked email within 90 days",
  },
  {
    id: "highly-engaged",
    name: "🔥 Highly Engaged",
    description: "Opened email 5+ times in last 30 days",
    category: "Engagement & Activity",
    icon: "🔥",
    definition: "5+ email opens in 30 days",
  },
  {
    id: "recent-clickers-90",
    name: "👆 Recent Email Clickers (Last 90 Days)",
    description: "Clicked email in last 90 days",
    category: "Engagement & Activity",
    icon: "👆",
    definition: "Clicked email within 90 days",
  },
  {
    id: "engaged-non-buyers",
    name: "💡 Engaged Non-Buyers",
    description: "Opens/clicks emails but never purchased",
    category: "Engagement & Activity",
    icon: "💡",
    definition: "Engaged but 0 purchases all time",
  },
  {
    id: "active-site-30",
    name: "🌐 Active on Site (Last 30 Days)",
    description: "Active on site in last 30 days",
    category: "Engagement & Activity",
    icon: "🌐",
    definition: "Site activity within 30 days",
  },
  {
    id: "unengaged-90",
    name: "😴 Unengaged (90+ Days)",
    description: "No opens in last 90 days",
    category: "Engagement & Activity",
    icon: "😴",
    definition: "No email opens in 90+ days",
  },
  {
    id: "unengaged-180",
    name: "💤 Unengaged (180+ Days)",
    description: "No opens in last 180 days",
    category: "Engagement & Activity",
    icon: "💤",
    definition: "No email opens in 180+ days",
  },
  {
    id: "email-openers-30",
    name: "👀 Email Openers (30 Days)",
    description: "Opened in last 30 days",
    category: "Engagement & Activity",
    icon: "👀",
    definition: "Email opens within 30 days",
  },
  {
    id: "email-openers-60",
    name: "👁️ Email Openers (60 Days)",
    description: "Opened in last 60 days",
    category: "Engagement & Activity",
    icon: "👁️",
    definition: "Email opens within 60 days",
  },
  {
    id: "email-clickers-30",
    name: "🖱️ Email Clickers (30 Days)",
    description: "Clicked in last 30 days",
    category: "Engagement & Activity",
    icon: "🖱️",
    definition: "Email clicks within 30 days",
  },
  {
    id: "email-clickers-60",
    name: "🖲️ Email Clickers (60 Days)",
    description: "Clicked in last 60 days",
    category: "Engagement & Activity",
    icon: "🖲️",
    definition: "Email clicks within 60 days",
  },
  {
    id: "site-visitors-30",
    name: "🏠 Site Visitors (30 Days)",
    description: "Visited site in last 30 days",
    category: "Engagement & Activity",
    icon: "🏠",
    definition: "Site visits within 30 days",
  },

  // DEMOGRAPHICS (8 segments)
  {
    id: "gender-male",
    name: "👨 Gender - Male",
    description: "Predicted gender likely male",
    category: "Demographics",
    icon: "👨",
    definition: "Predicted gender = male",
  },
  {
    id: "gender-female",
    name: "👩 Gender - Female",
    description: "Predicted gender likely female",
    category: "Demographics",
    icon: "👩",
    definition: "Predicted gender = female",
  },
  {
    id: "gender-uncertain",
    name: "❓ Gender - Uncertain",
    description: "Gender unknown",
    category: "Demographics",
    icon: "❓",
    definition: "Predicted gender = unknown",
  },
  {
    id: "location-country",
    name: "🌍 Location - By Country",
    description: "Filter by specific country",
    category: "Demographics",
    icon: "🌍",
    definition: "Country = [specified]",
  },
  {
    id: "location-proximity",
    name: "📍 Location - Proximity Radius",
    description: "Within X miles of location",
    category: "Demographics",
    icon: "📍",
    definition: "Within radius of coordinates",
  },
  {
    id: "birthday-month",
    name: "🎂 Birthday This Month",
    description: "Birthday in current month",
    category: "Demographics",
    icon: "🎂",
    definition: "Birthday month = current month",
  },
  {
    id: "age-18-24",
    name: "🧒 Age Group 18-24",
    description: "Born between specific dates for age range",
    category: "Demographics",
    icon: "🧒",
    definition: "Age between 18-24",
  },
  {
    id: "age-25-40",
    name: "🧑 Age Group 25-40",
    description: "Born between specific dates for age range",
    category: "Demographics",
    icon: "🧑",
    definition: "Age between 25-40",
  },

  // CUSTOMER LIFECYCLE & VALUE (15 segments)
  {
    id: "new-subscribers",
    name: "🌱 New Subscribers",
    description: "Joined list recently, never purchased",
    category: "Customer Lifecycle & Value",
    icon: "🌱",
    definition: "Subscribed recently, 0 purchases",
  },
  {
    id: "recent-first-time",
    name: "🎉 Recent First-Time Customers",
    description: "Made first purchase in last 30 days",
    category: "Customer Lifecycle & Value",
    icon: "🎉",
    definition: "First purchase within 30 days",
  },
  {
    id: "repeat-customers",
    name: "🔄 Repeat Customers",
    description: "2+ purchases all time",
    category: "Customer Lifecycle & Value",
    icon: "🔄",
    definition: "Order count ≥ 2",
  },
  {
    id: "one-time-buyers",
    name: "1️⃣ One-Time Customers",
    description: "Exactly 1 purchase all time",
    category: "Customer Lifecycle & Value",
    icon: "1️⃣",
    definition: "Order count = 1",
  },
  {
    id: "active-customers",
    name: "⚡ Active Customers",
    description: "Purchased in last 90 days",
    category: "Customer Lifecycle & Value",
    icon: "⚡",
    definition: "Purchase within 90 days",
  },
  {
    id: "lapsed-customers",
    name: "😴 Lapsed Customers",
    description: "Purchased before but not in last 180 days",
    category: "Customer Lifecycle & Value",
    icon: "😴",
    definition: "Last purchase 90-180 days ago",
  },
  {
    id: "churned-customers",
    name: "💔 Churned Customers",
    description: "No purchase in 365+ days",
    category: "Customer Lifecycle & Value",
    icon: "💔",
    definition: "No purchase in 365+ days",
  },
  {
    id: "vip-customers",
    name: "👑 VIP Customers",
    description: "5+ orders all time",
    category: "Customer Lifecycle & Value",
    icon: "👑",
    definition: "Order count ≥ 5",
  },
  {
    id: "big-spenders",
    name: "💰 Big Spenders",
    description: "Historic CLV greater than threshold",
    category: "Customer Lifecycle & Value",
    icon: "💰",
    definition: "CLV > threshold",
  },
  {
    id: "bargain-shoppers",
    name: "🏷️ Bargain Shoppers",
    description: "Historic CLV less than threshold",
    category: "Customer Lifecycle & Value",
    icon: "🏷️",
    definition: "CLV < threshold",
  },
  {
    id: "high-churn-risk",
    name: "⚠️ High Churn Risk",
    description: "Predictive analytics: high churn risk",
    category: "Customer Lifecycle & Value",
    icon: "⚠️",
    definition: "Predicted high churn probability",
  },
  {
    id: "likely-purchase-soon",
    name: "🎯 Likely to Purchase Soon",
    description: "Expected next order within 14 days",
    category: "Customer Lifecycle & Value",
    icon: "🎯",
    definition: "Predicted next order < 14 days",
  },
  {
    id: "predicted-vips",
    name: "⭐ Predicted VIPs",
    description: "High predicted CLV (next 365 days)",
    category: "Customer Lifecycle & Value",
    icon: "⭐",
    definition: "Predicted CLV high (365d)",
  },
  {
    id: "high-aov",
    name: "📈 High AOV",
    description: "Average order value greater than threshold",
    category: "Customer Lifecycle & Value",
    icon: "📈",
    definition: "AOV > threshold",
  },
  {
    id: "low-aov",
    name: "📉 Low AOV",
    description: "Average order value less than threshold",
    category: "Customer Lifecycle & Value",
    icon: "📉",
    definition: "AOV < threshold",
  },

  // SHOPPING BEHAVIOR & PURCHASE HISTORY (18 segments)
  {
    id: "all-customers",
    name: "🛍️ All Customers (PUR ≥ 1)",
    description: "Made at least 1 purchase",
    category: "Shopping Behavior & Purchase History",
    icon: "🛍️",
    definition: "Purchase count ≥ 1",
  },
  {
    id: "never-purchased",
    name: "👤 Never Purchased (Prospects)",
    description: "Zero purchases all time",
    category: "Shopping Behavior & Purchase History",
    icon: "👤",
    definition: "Purchase count = 0",
  },
  {
    id: "recent-purchasers-30",
    name: "🆕 Recent Purchasers (Last 30 Days)",
    description: "Purchased in last 30 days",
    category: "Shopping Behavior & Purchase History",
    icon: "🆕",
    definition: "Purchase within 30 days",
  },
  {
    id: "abandoned-cart",
    name: "🛒 Abandoned Cart",
    description: "Added to cart but didn't purchase (last 30 days)",
    category: "Shopping Behavior & Purchase History",
    icon: "🛒",
    definition: "Added to cart, no purchase 30d",
  },
  {
    id: "abandoned-cart-high-value",
    name: "💎 Abandoned Cart - High Value",
    description: "Cart value $400+ but no purchase",
    category: "Shopping Behavior & Purchase History",
    icon: "💎",
    definition: "Cart value $400+, no purchase",
  },
  {
    id: "abandoned-checkout",
    name: "🏁 Abandoned Checkout",
    description: "Started checkout but didn't complete",
    category: "Shopping Behavior & Purchase History",
    icon: "🏁",
    definition: "Started checkout, no order",
  },
  {
    id: "abandoned-checkout-high-value",
    name: "💵 Abandoned Checkout - High Value",
    description: "Checkout value $400+ but no complete",
    category: "Shopping Behavior & Purchase History",
    icon: "💵",
    definition: "Checkout $400+, no complete",
  },
  {
    id: "browse-abandonment",
    name: "👁️ Browse Abandonment",
    description: "Viewed product but didn't add to cart or purchase",
    category: "Shopping Behavior & Purchase History",
    icon: "👁️",
    definition: "Viewed product, no cart/purchase",
  },
  {
    id: "category-interest",
    name: "🔍 Category Interest",
    description: "Viewed specific category 2+ times but never purchased from it",
    category: "Shopping Behavior & Purchase History",
    icon: "🔍",
    definition: "2+ category views, 0 purchases",
  },
  {
    id: "product-interest",
    name: "🎁 Product-Specific Interest",
    description: "Viewed specific product 2+ times but never purchased it",
    category: "Shopping Behavior & Purchase History",
    icon: "🎁",
    definition: "2+ product views, not purchased",
  },
  {
    id: "cross-sell",
    name: "🔀 Cross-Sell Opportunity",
    description: "Purchased category X but not category Y",
    category: "Shopping Behavior & Purchase History",
    icon: "🔀",
    definition: "Purchased A, not B",
  },
  {
    id: "category-buyers",
    name: "📦 Category Buyers",
    description: "Purchased from specific category at least once",
    category: "Shopping Behavior & Purchase History",
    icon: "📦",
    definition: "Category purchase ≥ 1",
  },
  {
    id: "multi-category",
    name: "🎯 Multi-Category Shoppers",
    description: "Purchased from 2+ different categories",
    category: "Shopping Behavior & Purchase History",
    icon: "🎯",
    definition: "Purchased 2+ categories",
  },
  {
    id: "frequent-visitors",
    name: "🚀 Frequent Site Visitors",
    description: "Active on site 10+ times in last 30 days",
    category: "Shopping Behavior & Purchase History",
    icon: "🚀",
    definition: "10+ site visits in 30d",
  },
  {
    id: "coupon-users",
    name: "🎟️ Coupon Users",
    description: "Used discount code at least once",
    category: "Shopping Behavior & Purchase History",
    icon: "🎟️",
    definition: "Discount code used ≥ 1",
  },
  {
    id: "full-price-buyers",
    name: "💳 Full-Price Buyers",
    description: "Never used discount code",
    category: "Shopping Behavior & Purchase History",
    icon: "💳",
    definition: "Discount code used = 0",
  },
  {
    id: "product-reviewers",
    name: "⭐ Product Reviewers",
    description: "Left at least one review",
    category: "Shopping Behavior & Purchase History",
    icon: "⭐",
    definition: "Reviews ≥ 1",
  },
  {
    id: "non-reviewers",
    name: "📝 Non-Reviewers",
    description: "Purchased but never left review",
    category: "Shopping Behavior & Purchase History",
    icon: "📝",
    definition: "Purchases ≥ 1, reviews = 0",
  },

  // EXCLUSION SEGMENTS (12 segments)
  {
    id: "unsubscribed",
    name: "🚫 Unsubscribed Contacts",
    description: "Not subscribed to marketing",
    category: "Exclusion Segments",
    icon: "🚫",
    definition: "Marketing consent = false",
  },
  {
    id: "bounced-emails",
    name: "⚠️ Bounced Email Addresses",
    description: "Suppressed due to bounces",
    category: "Exclusion Segments",
    icon: "⚠️",
    definition: "Email bounced/suppressed",
  },
  {
    id: "not-opted-in",
    name: "❌ Not Opted-In Profiles",
    description: "Cannot receive marketing",
    category: "Exclusion Segments",
    icon: "❌",
    definition: "Not opted in to emails",
  },
  {
    id: "recent-purchasers-exclude",
    name: "🛑 Recent Purchasers (Exclusion)",
    description: "Purchased in last 14 days (exclude from promos)",
    category: "Exclusion Segments",
    icon: "🛑",
    definition: "Purchase within 14 days",
  },
  {
    id: "refunded-customers",
    name: "↩️ Refunded Customers",
    description: "Refunded order in last 30 days",
    category: "Exclusion Segments",
    icon: "↩️",
    definition: "Refund within 30 days",
  },
  {
    id: "negative-feedback",
    name: "😞 Negative Feedback",
    description: "Left review with 2 stars or less",
    category: "Exclusion Segments",
    icon: "😞",
    definition: "Review rating ≤ 2 stars",
  },
  {
    id: "unengaged-exclusion",
    name: "🔇 Unengaged Subscribers (Exclusion)",
    description: "No opens/clicks in 180+ days",
    category: "Exclusion Segments",
    icon: "🔇",
    definition: "No engagement 180+ days",
  },
  {
    id: "sunset-segment",
    name: "🌅 Sunset Segment",
    description: "Opened 1-3 times in last 180 days (low engagement)",
    category: "Exclusion Segments",
    icon: "🌅",
    definition: "1-3 opens in 180d",
  },
  {
    id: "high-churn-risk-exclude",
    name: "🚨 High Churn Risk (Exclusion)",
    description: "Predictive high churn risk",
    category: "Exclusion Segments",
    icon: "🚨",
    definition: "Predicted churn > threshold",
  },
  {
    id: "received-5-opened-0",
    name: "📪 Received 5, Opened 0",
    description: "Received 5+ emails but never opened any",
    category: "Exclusion Segments",
    icon: "📪",
    definition: "Received ≥ 5, opens = 0",
  },
  {
    id: "received-3-in-3-days",
    name: "📬 Received 3 in Last 3 Days",
    description: "Got 3+ emails in 72 hours (prevent fatigue)",
    category: "Exclusion Segments",
    icon: "📬",
    definition: "3+ emails in 72 hours",
  },
  {
    id: "marked-spam",
    name: "🗑️ Marked Spam",
    description: "Marked email as spam at least once",
    category: "Exclusion Segments",
    icon: "🗑️",
    definition: "Marked spam ≥ 1",
  },
];

export const BUNDLES = [
  {
    id: "core-essentials",
    name: "Core Essentials",
    description: "Essential segments every brand needs",
    segments: ["vip-customers", "repeat-customers", "one-time-buyers", "engaged-non-buyers", "abandoned-cart", "lapsed-customers"],
    icon: "🎯",
  },
  {
    id: "engagement-maximizer",
    name: "Engagement Maximizer",
    description: "All engagement and activity tracking segments",
    segments: ["engaged-30-days", "engaged-60-days", "engaged-90-days", "highly-engaged", "recent-clickers-90", "engaged-non-buyers", "active-site-30", "unengaged-90", "unengaged-180", "email-openers-30", "email-openers-60", "email-clickers-30", "email-clickers-60", "site-visitors-30"],
    icon: "📊",
  },
  {
    id: "lifecycle-manager",
    name: "Lifecycle Manager",
    description: "Complete customer lifecycle tracking",
    segments: ["new-subscribers", "recent-first-time", "repeat-customers", "one-time-buyers", "active-customers", "lapsed-customers", "churned-customers", "vip-customers", "big-spenders", "bargain-shoppers", "high-churn-risk", "likely-purchase-soon", "predicted-vips", "high-aov", "low-aov"],
    icon: "🔄",
  },
  {
    id: "shopping-behavior",
    name: "Shopping Behavior",
    description: "Track shopping patterns and opportunities",
    segments: ["browse-abandonment", "category-interest", "product-interest", "cross-sell", "category-buyers", "multi-category", "frequent-visitors", "coupon-users", "full-price-buyers"],
    icon: "🛍️",
  },
  {
    id: "smart-exclusions",
    name: "Smart Exclusions",
    description: "Suppression list for deliverability",
    segments: ["unsubscribed", "bounced-emails", "not-opted-in", "recent-purchasers-exclude", "refunded-customers", "negative-feedback", "unengaged-exclusion", "sunset-segment", "high-churn-risk-exclude", "received-5-opened-0", "received-3-in-3-days", "marked-spam"],
    icon: "🚫",
  },
];

export const CATEGORY_ICONS: Record<string, string> = {
  "Engagement & Activity": "📊",
  "Demographics": "👥",
  "Customer Lifecycle & Value": "💎",
  "Shopping Behavior & Purchase History": "🛍️",
  "Exclusion Segments": "🚫"
};

export const CATEGORIES = [
  "Engagement & Activity",
  "Demographics", 
  "Customer Lifecycle & Value",
  "Shopping Behavior & Purchase History",
  "Exclusion Segments"
];

export type Segment = typeof SEGMENTS[0];
export type Bundle = typeof BUNDLES[0];
